### PR TITLE
Changed CodiMD guide to SQLite

### PR DESCRIPTION
**Pull request by kindfulkirby**
CodiMD is not compatible with Uberspace's MySQL installation, running it with MySQL can lead to corruption of Unicode data like emoji.
SQLite does not have this problem, sadly I was not able to run CodiMD with a database in any other location than the folder it is run from, neither absolute nor relative paths work with it.

### CODE REVIEW

**Comment by SalocinHB** [comment]
What exactly is the problem with MySQL?

**Comment by kindfulkirby** [comment]
Oh, right I forgot to reference the issue. This fixes #271.

**Comment by SalocinHB** [comment]
The problem is most likely that the database is created with the `utf8` charset instead of `utf8mb4`.

[isabell@stardust ~]$ mysql -e "CREATE DATABASE <username>_codimd CHARACTER SET utf8 COLLATE utf8_general_ci;"`

**Comment by kindfulkirby** [comment]
That was the first thing I've tried. It results in one of the columns being too large for it's type, because now every character uses 4 bytes and Uberspace's MySQL isn't compiled with the right flags for that.

Maybe don't close this with a "most likely"?

**Comment by SalocinHB** [comment]
Are you sure you've tried that with MariaDB 10.3?

**Comment by SalocinHB** [comment]
Just tried it, works with 10.3.

**Pull request closed without merging**
