### PR TITLE
[Grocy] Fix paths and some steps.

### PR DESCRIPTION
**Pull request by jfowl**
While applying suggested changes in the original PR, I messed up some paths. This should fix them.

### CODE REVIEW

**Comment by luto** [comment]
As noted [in the original PR](https://github.com/Uberspace/lab/pull/740#discussion_r480069494), adding PHP code to your home directory won't work, because the web server is not allowed to access the files.

**Comment by jfowl** [comment]
@luto sorry, somehow i never got notifications about this from github. I'll need to check my settings.

Feel free to nuke this pr then.

**Comment by luto** [comment]
Okay :)

**Comment by luto** [comment]
wrong button m( reverted manually.

**Pull request merged**
