### PR TITLE
Add guide for vikunja

### LINKED ISSUE #1324: Guide for vikunja
URL: https://vikunja.io/

I can write a doku :)

### PR DESCRIPTION
**Pull request by SaschaMann**
Largely based on the Gitea guide, what's the preferred way of giving credit to it?

fixes #1324

### CODE REVIEW

**Comment by luto** [comment]
After installing the frontend files like so

```console
[little@lupus html]$ ls
[little@lupus html]$ wget https://dl.vikunja.io/frontend/vikunja-frontend-0.9.0.zip
--2023-02-16 12:00:27--  https://dl.vikunja.io/frontend/vikunja-frontend-0.9.0.zip
Resolving dl.vikunja.io (dl.vikunja.io)... 104.21.47.206, 172.67.172.167, 2606:4700:3034::ac43:aca7, ...
Connecting to dl.vikunja.io (dl.vikunja.io)|104.21.47.206|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3264725 (3.1M) [application/octet-stream]
Saving to: ‘vikunja-frontend-0.9.0.zip’

100%[===================>] 3,264,725   11.3MB/s   in 0.3s   

2023-02-16 12:00:28 (11.3 MB/s) - ‘vikunja-frontend-0.9.0.zip’ saved [3264725/3264725]

[little@lupus html]$ unzip vikunja-frontend-0.9.0.zip 
Archive:  vikunja-frontend-0.9.0.zip
 extracting: config.json             
   creating: css/
  inflating: css/app.4be21792.css    
  inflating: css/chunk-vendors.19d758a1.css  
  inflating: favicon.ico             
   creating: fonts/
  inflating: fonts/fonts.css         
(...)
[little@lupus html]$ ls
config.json  css  favicon.ico  fonts  images  img  index.html  js  manifest.json  precache-manifest.ae4433eb3b243ef58362edfaf50365e4.js  robots.txt  sw.js  workbox-v4.3.1
```

I am just getting this:
image
Maybe the backend config isn't complete yet? Or am I doing something wrong?

**Comment by EV21** [comment]
> Should I add an info box/note to the guide warning people about it?

Good idea. I think at least you should mention tested/compatible version like `Tested with Vikunja backend 0.20.2, frontend 0.20.3` or something.

In my point of view an even better way is to just add the instructions to install the frontend and mark them as `(optional)`.
I'm not sure if it is worth to do an extra guide just for the frontend, but this is something @luto has to decide :)
In this case I personally see these two components as one app even when they are technically seperated.

**Comment by luto** [comment]
Ah, yes, the download page sort is wacky.. using 0.20.3 yields better results! It now shows a login page and changes the URL in-browser to `/login`. That works, but if I then reload the page, _the server_ (rather than the JS app) replies with a 404 😅 Adding a `.htaccess` to send all requests to `index.html` for client-side URL routing seems to work:

```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ /index.html [NC,L,QSA]
```

What do you think?

**Comment by SaschaMann** [comment]
> What do you think?

I don't know if that has any unintended consequences but I'm happy to add instructions for installing the front-end in the guide directly and add that `.htaccess` example if that makes things more reliable.

**Comment by EV21** [comment]
> unintended consequences

I could reproduce that issue and lutos fix seems to work really great. I could not find any problems so far with a lot of clicking and hacking around with the app 😂.

**Comment by EV21** [comment]
I noticed some other things we may add to the guide

## user registration

As most users probably like to deactivate the web based user registration we may add this CLI Command to the guide
```console
[isabell@stardust ~]$ ~/vikunja/vikunja user create --username isabell --password 'SuperSecretPassword' --email isabell@uber.space
...
User was created successfully.
[isabell@stardust ~]$
```
---

## logging

I also noticed that the log configuration is very verbose so working with the CLI is no fun. - It looks like debug spam
- [ ] log configuration

suggestion
```yml
log:
  # Change the log level. Possible values (case-insensitive) are CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG.
  level: "WARNING"
  # The log level for database log messages. Possible values (case-insensitive) are CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG.
  databaselevel: "WARNING"
  # The log level for event log messages. Possible values (case-insensitive) are ERROR, INFO, DEBUG.
  eventslevel: "ERROR"
```

## mailer
If the app also gives notifications (reminders) and stuff it also makes sense to configure and activate the mailer
- [ ] mailer configuration

suggestion
```yml
service:
  # The URL of the frontend, used to send password reset emails.
  frontendurl: "https://isabell.uber.space"

mailer:
  # Whether to enable the mailer or not. If it is disabled, all users are enabled right away and password reset is not possible.
  enabled: true
  # SMTP Host
  host: "stardust.uberspace.de"
  # SMTP Host port.
  port: 587
  # SMTP username
  username: "isabell@uber.space"
  # SMTP password
  password: "SuperSecretMailPassword"
  # The default from address when sending emails
  fromemail: "isabell@uber.space"
```

**Comment by SaschaMann** [comment]
I think those commits address all suggestions, let me know if anything is missing.

I've kept the frontend guide as its own step rather than putting it into `Optional steps` even if it's technically an optional step. Pointing out how to actually access Vikunja seems important, even if users decide they don't want to use the web frontend.

**Comment by luto** [comment]
SWEET! Thank you :)

**Pull request merged**
