### PR TITLE
Add guide for Mailman 3

### LINKED ISSUE #141: add a guide for Mailman3
GNU Mailman is a computer software application from the GNU Project for managing electronic mailing lists. Mailman is coded primarily in Python and currently maintained by Abhilash Raj. Mailman is free software, licensed under the GNU General Public License.

http://docs.mailman3.org/en/latest/

### PR DESCRIPTION
**Pull request by rikroe**
Fixes #141. 
A lot of discussion has taken place in PR #311. This is an updated version of the original pull request. 

A guide for Mailman 3 on U7. Has been tested on a clean U7 but requires quite a lot of configuration and some helper scripts.

Looking forward to your feedback! 😄 

Thanks @luto for your patience and help!

### CODE REVIEW

**Comment by luto** [comment]
Looks great :tada: :)

FYI: We finally got proper links to manual and lab articles in #325 using `:manual:` and `:lab:`. Please review the issue or [the styleguide](https://github.com/Uberspace/lab/blob/master/STYLE.md) for details. So there is no need to have absolute URLs to manual.uberspace.de anymore.

**Comment by rikroe** [comment]
Ah, haven't checked the latest commits 😅
Will change those but probably won't be able to do so until the weekend. 
BTW, would you prefer one single commit containing all changes?

**Comment by rikroe** [comment]
Got a chance to update the `:manual:` and `:lab:` directives 🎉 

However got a warning/info mail regarding the new _web backends_ and our new supervisorctl `runner` script. I don't see an issue because the Mailman Core REST api as well as the LMTP server should only be available under one's own localhost (so, great change for more security 🔝). 
Did I understand this part correctly? Otherwise we need to wait until 11th to check it out :)

**Comment by luto** [comment]
:tada: yay! merged :grin: Thanks so much for all the work :)

I also went ahead and renamed the mailman 2 guide to "Mailman 2" and added a hint about the newer version.

**Pull request merged**
