### PR TITLE
Update guide_selfoss.rst

### PR DESCRIPTION
**Pull request by cblte**
added section if user wants to put selfoss into a subdomain.

### CODE REVIEW

**Comment by SalocinHB** [comment]
Setting up subdomains is explained in the manual.

**Comment by cblte** [comment]
this is not about adding or setting up a subdomain. it describes a configuration setting you need to set when you use Selfoss with a subdomain and not in a subdirectory to html. Maybe this was a misunderstanding.

**Comment by nichtmax** [comment]
All guides are for a fresh account and all tools have to be installed into the main DocumentRoot due to simplicity and uniformity.

**Comment by cblte** [comment]
> All guides are for a fresh account and all tools have to be installed into the main DocumentRoot due to simplicity and uniformity.

I fully agree. I added this just as additional information. maybe the wording is not the best. will think about it and redo.

**Pull request closed without merging**
