### PR TITLE
[Gancio] Add installation guide for gancio

### PR DESCRIPTION
**Pull request by xJohnDoe993**

### CODE REVIEW

**Comment by nichtmax** [comment]
@xJohnDoe993 please get in touch via hallo@uberspace.de for your mug that you'll get in any case ☺️

**Comment by xJohnDoe993** [comment]
Hey @nichtmax, 
thanks for your work.
I will try to get in touch with the Gancio Team on framagit and will ask about the issue with the eol node version, may they will work on that soon. Otherwise i guess we need to skip the gancio guide for now.
Sorry for the inconvenience, i didnt know that node 16 will be eol soon and thought gancio would be a nice addition to the uberlab catalog.

**Comment by nichtmax** [comment]
> I will try to get in touch with the Gancio Team on framagit and will ask about the issue with the eol node version, may they will work on that soon. 

That's great, thank you!

> Otherwise i guess we need to skip the gancio guide for now.

I talked with my colleagues about the issue and we would like to wait with merging your PR until Gancio is compatible with newer versions of NodeJS. Is that alright with you?

> Sorry for the inconvenience, i didnt know that node 16 will be eol soon and thought gancio would be a nice addition to the uberlab catalog.

No inconvenience at all from our side! I didn't know about Gancio and it looks very promising! We would love to have a guide!

**Comment by xJohnDoe993** [comment]
@nichtmax of course it is. I allready got feedback
 
> Thanks for pointing this out. I think that will be pretty easy to upgrade, there are no huge breaking changes... I've tried it now very quickly and all test pass so probably the next release will be node v18 compatible

So its a matter of time :)

**Comment by nichtmax** [comment]
That's a win-win! Great! ☺️

**Comment by xJohnDoe993** [comment]
@nichtmax Gancio 1.6.14 released on 30th of June and has support for node v18
https://gancio.org/changelog#1614---30-june-23
May i will find the time later to change the installation guide

**Pull request merged**
