### PR TITLE
Guide framadate

### PR DESCRIPTION
**Pull request by Marmo**
Created a guide for Framadate (#400 )

### CODE REVIEW

**Comment by luto** [comment]
Works great, except for sending emails :sweat_smile: I'll need to take a closer look later.

**Comment by Marmo** [comment]
Right, I disabled the email-functions as I don't need them. But I will have a look, too and try to get email working.

**Comment by Marmo** [comment]
Ok I got mail working. Can I add commits to the pull request somehow, or should I create a new pull request (but what would happen with your changes then?)

**Comment by luto** [comment]
> Can I add commits to the pull request somehow, or should I create a new pull request (but what would happen with your changes then?)

First run `git checkout guide-framadate` to make sure you're on the right branch. Then, execute `git pull` to get my changes. After that you can add commits as you already did in the first round. If you used the github web interface, you can directly edit the files [in your branch](https://github.com/Marmo/lab/tree/guide-framadate).

Thanks for looking into this!

**Comment by luto** [comment]
Thank you! Mail works perfectly now :tada: 

Since github won't let me merge this in the GUI, I rebased and merged manually.

**Pull request closed without merging**
