### PR TITLE
Guide for GSALES 2 and IonCube Loader (PHP7.1) on Uberspace

### PR DESCRIPTION
**Pull request by gsirin**
HowTo Install and Setup GSALES 2 and IonCube Loader Extension for PHP 7.1 on Uberspace 7

### CODE REVIEW

**Comment by gsirin** [comment]
I think that is good idea. Should I quickly write a first draft?

**Comment by luto** [comment]
Take all the time you need :)

**Comment by gsirin** [comment]
Maybe one day I will understand how to link from one guide to another .... :)
Help appreciated...

**Comment by luto** [comment]
I took care of the links :) feel free to have a look!

**Comment by gsirin** [comment]
Thank you! Looks pretty good now, I think...

**Comment by gsirin** [comment]
> oh. 😂 sorry 😁

no worries 👍

**Comment by luto** [comment]
Thanks @SalocinHB :)

**Pull request merged**
