### PR TITLE
Add guide for tor onion service

### PR DESCRIPTION
**Pull request by expiringplatform**
Hello everyone, 
I wrote a little guide how to install tor and setup an onion service in your uberspace.
I hope it might be helpful. :)
I'm very new to the used .rst format, so probably I made some errors in the style/formatting. I'm looking forward to any feedback! :)

### CODE REVIEW

**Comment by nichtmax** [comment]
Please add 
```
ExitPolicy reject *:*
```
to the config, we don't want any exit nodes.

**Comment by nichtmax** [comment]
I can't start the binary, I get the following error: 
```
./tor/tor: error while loading shared libraries: libevent-2.1.so.7: cannot open shared object file: No such file or directory
```

**Review by nichtmax — CHANGES_REQUESTED** [review]
I can't get Tor so start, do you have a hint maybe?

**Comment by expiringplatform** [comment]
> I can't start the binary, I get the following error:
> 
> ```
> ./tor/tor: error while loading shared libraries: libevent-2.1.so.7: cannot open shared object file: No such file or directory
> ```

Hi, thank you for the feedback and sorry for the late reply. 

@nichtmax  This error is expected. Tor dependends on some libraries that are shipped by torproject together with the tor binary. The start the tor binary the LD_LIBRARY_PATH has to be set accordingly. You can try:

`LD_LIBRARY_PATH=~/tor ~/tor/tor --torrc-file tor/torrc`

This command in also contained in the bottom of the guide in the Debugging section. I see that it might be confusing to people who follow the guide and then recognize that the binary can not be started. Do you think it would be useful to mention this command somewhere more prominent, like right before the "Setup the daemon" section. 

@SalocinHB Thanks for adding the exit policy to the config. I omitted it because I without checking assumed that this would be the implicit default when this option is not set in the config file.

**Comment by nichtmax** [comment]
I apologize that it has taken so long. I had an exceptional personal situation and have hardly been able to get anything done in the last few weeks. 

I added a note about `LD_LIBRARY_PATH`.

**Comment by expiringplatform** [comment]
Thanks for adding the explanation, that makes it way more clear what is happening.
No problem at all, don't worry. I just hope you are well. Great that this got merged, thanks! 🥳

**Pull request merged**
