### PR TITLE
[OwnTracks] Created guide

### PR DESCRIPTION
**Pull request by schneidr**
I've written up my OwnTracks installation as a lab guide. It's a little extensive, and is not really for beginners as it requires people to compile their own binaries, but it's not that difficult.

### CODE REVIEW

**Comment by nichtmax** [comment]
Just a quick heads up: We will review your PR in January, we're a bit understaffed in support and we all need a few days off for Christmas 🎄 🤶

**Comment by SalocinHB** [comment]
I don't think we can accept the guide in this form, but if you let us know which header files are missing we'll check if we can provide them.

**Comment by schneidr** [comment]
That would be awesome, it would make the process so much easier. `libuuid-devel` and `lua-devel` are already installed, that leaves:

- mosquitto-devel
- libcurl-devel
- libsodium-devel
- libconfig-devel
- lmdb-devel

**Comment by SalocinHB** [comment]
> That would be awesome, it would make the process so much easier. `libuuid-devel` and `lua-devel` are already installed, that leaves:
> 
> * mosquitto-devel
> * libcurl-devel
> * libsodium-devel
> * libconfig-devel
> * lmdb-devel

yum says libcurl-devel is obsoleted by the curl RPM which is already installed. We'll provide the rest with the next U7 release.

**Comment by SalocinHB** [comment]
@schneidr we have rolled out the binaries, would you like to try and rewrite your guide accordingly?

**Comment by kimdiallo** [comment]
Flawless, thank you very much for your effort, @schneidr

**Comment by nichtmax** [comment]
@schneidr Did you get a goodie? If not please get in touch via hallo@uberspace.de, I'm sorry, I somehow lost track ☺️

**Pull request merged**
