### PR TITLE
changed to supervisord snippet

### PR DESCRIPTION
**Pull request by 927589452**
Fixing #414

### CODE REVIEW

**Comment by 927589452** [comment]
@luto this fixes #414

**Comment by luto** [comment]
WOHA! Thank you so much!

**Comment by FriedrichFroebel** [comment]
Just out of curiosity: Why does this PR remove `supervisord` from the basic concepts? Shouldn't one still be familiar with it for following the guide?

**Comment by luto** [comment]
It removes it from a couple of guides that claimed to use it, but didn't. Apparently a few ones like django use it, but a bit differently, so they went unnoticed. I'll re-add the note later. Thanks for the heads-up!

**Comment by 927589452** [comment]
basically i just searched for supervisord @FriedrichFroebel and if I didn't find any mention in the code i remove the reference
if I found a mention I search for the reread part and replaced it with the include

**Pull request merged**
