### PR TITLE
[actual] add guide for Actual Budget

### PR DESCRIPTION
**Pull request by knhash**
Closes https://github.com/Uberspace/lab/issues/1668

[Actual Budget](https://actualbudget.org) is a super fast and privacy-focused app for managing your finances.

### CODE REVIEW

**Comment by nichtmax** [comment]
Just a quick heads up: We will review your PR in January, we're a bit understaffed in support and we all need a few days off for Christmas 🎄 🤶

**Comment by SalocinHB** [comment]
@knhash thank you for your guide. I've done some modifications and published it. Please contact hallo@uberspace.de to receive a voucher for your goodie.

**Comment by knhash** [comment]
@SalocinHB something seems off though, the guide exists at https://lab.uberspace.de/actual but doesn't show up in the side bar...

**Comment by SalocinHB** [comment]
> @SalocinHB something seems off though, the guide exists at https://lab.uberspace.de/actual but doesn't show up in the side bar...

Yup, the file name was off. Needs to be `guide_actual.rst` which then translates to https://lab.uberspace.de/guide_actual and an entry in the side bar.

**Pull request merged**
