### PR TITLE
Fix typos and spelling inconsistencies in guide_etherpad

### PR DESCRIPTION
**Pull request by eltenedor**

### CODE REVIEW

**Comment by eltenedor** [comment]
Some of the "typos" I corrected may have originated from the boilerplate: https://github.com/Uberspace/lab/blob/main/STYLE.md : 

* setup (noun) vs. set up (verb) (see "Your blog URL needs to be setup")
* "Configure Webserver" vs. "Configure web server" (spelling, consistent capitalization and )
* Setup Demon vs. Set up demon 
* Consistent use of articles in titles ("Download the source" vs. "Configure web( )server"

**Comment by luto** [comment]
Thanks!

**Comment by luto** [comment]
@eltenedor are you up for submitting another pull request fixing STYLE.md? :)

**Comment by eltenedor** [comment]
> @eltenedor are you up for submitting another pull request fixing STYLE.md? :)

Yes, will do! I think I forgot to link this pull request, to issue #961 should I open up a new issue for STYLE.md @luto ?

**Comment by luto** [comment]
just a pull request without issue is fine :)

**Pull request merged**
