### PR TITLE
[etherpad] add broken message

### PR DESCRIPTION
**Pull request by no-one**
see #1754

### CODE REVIEW

**Comment by no-one** [comment]
Closed as @bugtrapper is working on a fix: https://github.com/Uberspace/lab/pull/1757

**Comment by Uatschitchun** [comment]
As admin panel isn't working since 2.0.x, the guide is broken atm!

See #1754

**Comment by bugtrapper** [comment]
Sorry that this slipped through. It's working in my installation, but I obviously forgot to include a necessary step. I will update the PR accordingly.

**Comment by no-one** [comment]
Yes, but there is no longer any need for a _broken message_ because a fix will be available soon.

**Pull request closed without merging**
