### PR TITLE
Fix some spelling errors and trim trailing whitespace

### PR DESCRIPTION
**Pull request by toddy15**
Hi,

this PR fixes some spelling mistakes. If you don't want the trailing whitespace removed, I can submit another PR without those changes.

Regards,
Tobias

### CODE REVIEW

**Comment by knhash** [comment]
Would it be a good idea to also rename guide_bitwarden.rst to guide_vaultwarden.rst as part of this PR, so it takes its right place in the sorted list?

**Comment by toddy15** [comment]
Yes, I could do that -- and I think it's sensible. However, I'm not sure if Uberspace wants this, so I won't do it now. @noave, I've seen that you've just merged #1170 -- should I include the renaming in this PR?

**Comment by nichtmax** [comment]
Thanks @toddy15, that's awesome! I'm ready to merge, feel free to rename `guide_bitwarden.rst` to `guide_vaultwarden.rst`.

**Comment by toddy15** [comment]
@nichtmax Great, thanks. I've renamed the file and force-pushed with the latest changes in main.

**Comment by SalocinHB** [comment]
Because I just saw this: `organisations` is not a spelling mistake. There is a somewhat weird country called the United Kingdom where people spell words in ways unimaginable to US Americans.

https://www.merriam-webster.com/dictionary/organisation

**Pull request merged**
