### PR TITLE
[meta] added missing language tags

### PR DESCRIPTION
**Pull request by schneidr**
I updated allmost all guides in the list where the tags where missing (some were already added).

I was unable to find the language of Resilio Sync, Teamspeak, as they are proprietary and only provide binaries.

The Web Key Directory (WKD) doesn't really have a language, as it's only a defined directory structure for PGP files.

I was unable to commit the guides for couchdb and gancio because they are missung the `Tested on Uberspace` part and I'm currently unable to do the tests myself.

The tags would be:

CouchDB

```
.. tag:: Erlang
```

gancio:

```
.. tag:: lang-php
.. tag:: lang-nodejs
```

#1612

### CODE REVIEW

**Comment by nichtmax** [comment]
Hey @schneidr, thank you, that's awesome!

All guides here are tested be us, couchdb and gancio are tested as well, there's just the section missing then.

**Comment by schneidr** [comment]
> All guides here are tested be us, couchdb and gancio are tested as well, there's just the section missing then.

I can of course just add the sections, but I did not want to make up some version numbers :/

**Comment by nichtmax** [comment]
> > All guides here are tested be us, couchdb and gancio are tested as well, there's just the section missing then.
> 
> I can of course just add the sections, but I did not want to make up some version numbers :/

Ah now I get the problem. 

Ganico v1.6.14 / U7.15.4.0

the couchdb binaries are from us and we got testing for it in our release process. Every binary that makes in into production will work. The guide for the configuration is tested with U7.10.0

**Comment by schneidr** [comment]
With all guides updated this closes #1612.

**Comment by nichtmax** [comment]
Thank you! Check your mails ☺️

**Pull request merged**
