### PR TITLE
:lipstick: only show scrollbars for guide section in side nav

### PR DESCRIPTION
**Pull request by brutus**
adds scrolling [as suggested](https://github.com/Uberspace/lab/pull/1070), but only for the guides section instead the whole side navigation.

### CODE REVIEW

**Comment by kraftner** [comment]
Yeah, sure, why not. Maybe making the scrollbar a little less invasive is an option too: https://css-tricks.com/the-current-state-of-styling-scrollbars/

**Comment by brutus** [comment]
Yes! definitly :) Was just a quick test in Firefox to gather feedback… I just noticed now how ugly this is in Chromium :sweat_smile:

**Comment by kraftner** [comment]
( :+1: for using Firefox as primary browser! )

I am glad you're working on it and the approach sounds good to me.  So, I guess you'll do great from here, I'm dropping out here and go back to my work ;)

**Comment by brutus** [comment]
UX opinion came in, not in favour of only scrolling the guides; we now scroll the whole navigation - but not the sidebar head (with logo and search). Also some :lipstick: to bring Chrome (Edge, Safari…) more in line with Firefox scrollbar design.

**Comment by kraftner** [comment]
:heart_eyes:

**Pull request merged**
