### PR TITLE
Update Python and PyPI packages, fix errors and warnings

### PR DESCRIPTION
**Pull request by toddy15**
Hi Uberspace team,

I have Python 3.12 installed on my computer, so I wasn't able anymore to build the lab locally, because the `imp` library is not supported (see https://github.com/Uberspace/lab/pull/1740#issue-2190844007).

As the Sphinx version (4.4) in use is rather old, I've looked into updating Sphinx to the current version (8.0) and also updated the dependencies to their latest versions.

While at it, I fixed all reported errors and warnings (which are reported with Sphinx 4.4 as well, so those are not due to the update).

I'm able to build the lab locally now, without any warnings or errors. The generated HTML output looks good to me, I didn't spot any obvious errors or wrong formats in the output. However, I didn't verify *all* HTML files, just picked some examples.

From what I can tell, the minimum supported Python version seems to be 3.10 now, so if you want to loosen the requirement on Python 3.12 a bit, I'm happy to make that adjustment.

Regards,
Tobias

### CODE REVIEW

**Comment by nichtmax** [comment]
The Netlify Build image only has Python 3.8 (thats why the build fails), we'll haven to throw some time at this.

**Comment by nichtmax** [comment]
@luto any idea besides installing our own Python with every build?

**Comment by toddy15** [comment]
Hm, I guess the move away from Netlify won't happen anytime soon. I've therefore created another PR (#1823), which updates the tooling up to the latest Sphinx version supporting Python 3.8. Moreover, all of the fixes for errors and warnings from this PR have been included in the new PR.

**Comment by toddy15** [comment]
After #1823 has been merged, this PR can be closed. There are only the first two commits left, which currently are not working with Netlify.

Regards,
Tobias

**Pull request closed without merging**
