### PR TITLE
[gitea] added guide to perfom updates using an automated script

### PR DESCRIPTION
**Pull request by mschabhuettl**
As suggested on Twitter, I'm going to provide you with a guide to use an automated script for Gitea updates.

### CODE REVIEW

**Comment by EV21** [comment]
Hi @mschabhuettl,
this is a nice script. :+1: 
It would be even more nice if the script also checks if the locally installed version matches the latest online one. 
I was wondering about the grep expression for the version string. So you got it from of the http location tag. :thinking: 
You can just call the GitHub-API for this.

```bash
GITHUB_API_URL=https://api.github.com/repos/go-gitea/gitea/releases/latest
curl --silent $GITHUB_API_URL > ~/tmp/github_api_response.json

jq --raw-output '.assets[].browser_download_url' ~/tmp/github_api_response.json | grep --max-count=1 "linux-amd64"
#https://github.com/go-gitea/gitea/releases/download/v1.13.1/gitea-1.13.1-linux-amd64
jq --raw-output '.assets[].browser_download_url' ~/tmp/github_api_response.json | grep "linux-amd64.asc"
#https://github.com/go-gitea/gitea/releases/download/v1.13.1/gitea-1.13.1-linux-amd64.asc
```

`gitea --version` should work for this.

get LOCAL:
```bash
./gitea --version | awk '{print $3}' # since gitea tells us a love story we have to filter here
1.13.1
```
get LATEST:

```bash
GITHUB_API_URL=https://api.github.com/repos/go-gitea/gitea/releases/latest
curl --silent $GITHUB_API_URL > ~/tmp/github_api_response.json
TAG_NAME=$(jq --raw-output '.tag_name' ~/tmp/github_api_response.json)

echo ${TAG_NAME} # Whos idea was that with the v-prefix? :confused: 
v1.13.1

echo ${TAG_NAME:1:6} # using substring
1.13.1

LATEST=${TAG_NAME:1:6}
```

something like this for the check:
```bash
  if [ "$LOCAL" = "$LATEST" ]; then
    echo "Your Gitea is already up to date."
  else
    if [[ "$LOCAL" < "$LATEST" ]]; then
      echo "There is a new Version available. - Updating..."
      supervisorctl stop gitea
      ...
    fi
  fi
```

**Comment by mschabhuettl** [comment]
> Hi @mschabhuettl,
> this is a nice script. +1
> It would be even more nice if the script also checks if the local installed version matches the latest online one.
> I was wondering about the grep expression for the version string. So you got it from of the http location tag. thinking
> You can just call the GitHub-API for this.
> 
> ```shell
> GITHUB_API_URL=https://api.github.com/repos/go-gitea/gitea/releases/latest
> curl --silent $GITHUB_API_URL > ~/tmp/github_api_response.json
> 
> jq --raw-output '.assets[].browser_download_url' ~/tmp/github_api_response.json | grep --max-count=1 "linux-amd64"
> #https://github.com/go-gitea/gitea/releases/download/v1.13.1/gitea-1.13.1-linux-amd64
> jq --raw-output '.assets[].browser_download_url' ~/tmp/github_api_response.json | grep "linux-amd64.asc"
> #https://github.com/go-gitea/gitea/releases/download/v1.13.1/gitea-1.13.1-linux-amd64.asc
> ```
> 
> `gitea --version` should work for this.
> 
> get LOCAL:
> 
> ```shell
> ./gitea --version | awk '{print $3}' # since gitea tells us a love story we have to filter here
> 1.13.1
> ```
> 
> get LATEST:
> 
> ```shell
> GITHUB_API_URL=https://api.github.com/repos/go-gitea/gitea/releases/latest
> curl --silent $GITHUB_API_URL > ~/tmp/github_api_response.json
> TAG_NAME=$(jq --raw-output '.tag_name' ~/tmp/github_api_response.json)
> 
> echo ${TAG_NAME} # Whos idea was that with the v-prefix? :confused: 
> v1.13.1
> 
> echo ${TAG_NAME:1} # using substring beginning at index 1 (skipping 0=v)
> 1.13.1
> 
> LATEST=${TAG_NAME:1}
> ```
> 
> something like this for the check:
> 
> ```shell
>   if [ "$LOCAL" = "$LATEST" ]; then
>     echo "Your Gitea is already up to date."
>   else
>     if [[ "$LOCAL" < "$LATEST" ]]; then
>       echo "There is a new Version available. - Updating..."
>       supervisorctl stop gitea
>       ...
>     fi
>   fi
> ```

You're right @EV21 - This is even more nice! :+1: 
Thank you very much for your input! I'm going to implement that!
Have a nice day! :+1:

**Comment by luto** [comment]
@mschabhuettl are you still planning to implement the suggested changes? :)

**Comment by luto** [comment]
closed for inactivity. feel free to reopen or start a new PR!

**Pull request closed without merging**
